"""Write assets/MANIFEST.csv: what every input file is, how big, its digest, and where it came from.

Run from the repo root:  python scripts/make_manifest.py
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from fastcad.assets import digest, scan  # noqa: E402

#: where each group of files came from, for the provenance column
SOURCES: dict[str, str] = {
    "target": "NREL GRC GB3 (OEDI submission 56, DOI 10.7799/1337868); the STEP is the user's Onshape export",
    "target/parent": "NREL GRC GB2 (OEDI submission 45, DOI 10.7799/1254154)",
    "target/deck": "fastcae assets/GRC_Gearbox_Housing (deck generated by fastcae's bench script)",
    "context/drawings/gb3": "NREL GRC GB3, 2D Drawings.zip",
    "context/drawings/gb2": "NREL GRC GB2, 2D Drawings.zip",
    "context/reference": "fastcae: production ribs removed in Onshape; the answer key for rib recognition",
    "tech-data/reports": "NREL GRC reports (grc-common, grc-gb2, grc-gb3)",
    "tech-data": "written by this project from the reports and drawings, with source and page per value",
}


def source_for(rel: Path) -> str:
    parent = rel.parent.as_posix()
    while parent and parent != ".":
        if parent in SOURCES:
            return SOURCES[parent]
        parent = parent.rsplit("/", 1)[0] if "/" in parent else ""
    return ""


def main() -> int:
    assets = ROOT / "assets"
    index = scan(assets)
    rows = []
    for a in sorted(index.assets, key=lambda x: x.path.as_posix()):
        rows.append({
            "path": a.path.as_posix(),
            "role": a.group,
            "kind": a.kind,
            "selected_by_default": "yes" if a.selected else "no",
            "bytes": a.size_bytes,
            "sha256": digest(assets / a.path),
            "source": source_for(a.path),
            "note": a.note,
        })

    out = assets / "MANIFEST.csv"
    with out.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0]))
        w.writeheader()
        w.writerows(rows)

    picked = [r for r in rows if r["selected_by_default"] == "yes"]
    print(f"{len(rows)} files, {index.total_bytes() / 1e6:.1f} MB -> {out}")
    print(f"selected by default: {len(picked)} files, {index.total_bytes(only_selected=True) / 1e6:.1f} MB")
    for r in picked:
        print(f"  {r['kind']:9s} {r['path']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
